#!/bin/bash
#
#
echo -n "Sisesta kuu number: "
read kuu #loeb sisestatud arvu
if [ $kuu -ge 1 -a $kuu -le 2 -o $kuu -eq 12 ]; then #kui arv on vahemikus 1-2 või võrdub 12 siis väljastab et praegu on talv
	echo "Praegu on talv"
elif [ $kuu -ge 3 -a $kuu -le 5 ]; then #kui arv on vahemikus 3-5 siis väljastab et praegu on kevad
	echo "Praegu on kevad"
elif [ $kuu -ge 6 -a $kuu -le 8 ]; then #kui arv on vahemikus 6-8 siis väljastab et praegu on suvi
	echo "Praegu on suvi"
elif [ $kuu -ge 9 -a $kuu -le 11 ]; then #kui arv on vahemikus 9-11 siis väljastab et praegu on sügis
	echo "Praegu on sügis"
else #kui vahemikkudes olevat numbrit pole väljastab et sellist kuud ei ole olemas
	echo "Sellist kuud ei ole olemas"
fi
