#!/bin/bash
#
#
jaak=$( expr $1 % 2 )
if [ -z "$1" ]; then #kui ei sisestatud midagi siis võtab seda tõesena ja vasab ei unustasite sisestada arvu käsureale
	echo "Unustasite sisestada arvu käsureale"
elif [ "$jaak" -eq "0" ]; then #kui tehtel ei jää jääki siis vastab et antud arv on paaris
	echo "Antud arv on paaris"
else #kui tehtel jääb jääk siis vastab et antud arv on paaritu
	echo "Antud arv on paaritu"
fi
