#!/bin/bash
#
#
for (( arv=1; arv<11; arv++ )) #alustab arvust 1, lõpetab 11-ga ja liidab ühe juurde
do
	jaak=$(( $arv % 2 )) #arv jagatakse kahega ja vaadatakse jääki
	if [ $jaak -eq 0 ]; then #kui jääk puudub siis...
		summa=$(( $summa + $arv )) #...liidetakse jäägita arv koos eelmiste arvudega kokku
	fi
done
echo "arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa" #kuvatakse summa kokku
