#!/bin/bash
#
#
echo -n "Sisesta suvaline täisarv: "
read taisarv #loeb sisestatud arvu
summa=0 #summa on 0
while [ $taisarv -ne 0 ] #kui täisarv ei võrdu 0
do
	jaak=$(( $taisarv % 10 )) #täisarv jagatakse 10-ga ja leitakse jääk
	taisarv=$(( $taisarv / 10 )) #täisarv jagatakse 10-ga
	summa=$(( $summa + $jaak )) #arvutatakse summa kui liidetakse jäägile eelmiste jääkide osad
done
echo "Arvu numbrite summa on $summa" #trükib arvude summa välja
