#!/bin/bash
#
# var kaustast .log lõpuga otsimise skript
find /var/ -name *.log 2>/dev/null -exec wc -l {} \; | sort -n -r
# find /kaust/ -mille järgi *.faili tüüp 2>/dev/null(errorite vältimiseks)
# wl -l loendab ridade arvu
# sorteerib ridade arvu järgi kahanevalt
