#!/bin/bash
#
#
echo -n "Sisesta a kylje vaartus:"
read a
echo -n "Sisesta b kylje vaartus:"
read b
echo -n "Sisesta c kylje vaartus:"
read c
ymber=$(echo "scale=3;($a+$b+$c)/2" | bc) #arvutasin pool ümbermõõtu
aa=$(echo "$ymber-$a" | bc) #ümbermõõt miinus külg
bb=$(echo "$ymber-$b" | bc) #ümbermõõt miinus külg
cc=$(echo "$ymber-$c" | bc)
korda=$(echo "$ymber*$aa*$bb*$cc" | bc) #korrutasin kõik
vastus=$(echo "scale=3;sqrt($korda)" | bc) #arvutasin vastuse
echo "Pindala = $vastus"

