#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv reads: "
read tarnid
for (( a=1; a<=$rida; a++ )) #arvutab ridade arvu
do
	for(( b=1; b<=$tarnid; b++ )) #arvutab märkide arvu reas
	do
		echo -n "* " #väljastab * mitu korda ja mitu rida on märgitud
	done
echo "" #tühi rida
done
