#!/bin/bash
#
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv reads: "
read tarnid
for (( a=1; a<=$rida; a++ )) #arvutab ridade arvu
do
	for(( b=1; b<=$tarnid; b++ )) #arvutab märkide arvu reas
	do
	if [ $a -eq 1 -o $a -eq $rida ]; then #kui a võrdub 1 või kui a võrdub ridade arvuga, siis...
	echo -n "*" #trükib tärni
	elif [ $b -eq 1 -o $b -eq $tarnid ]; then #kui b võrdub 1 või kui b võrdub tärnide arvuga, siis...
	echo -n "*" #trükib tärni
	else #kui väide on vale, siis...
	echo -n " " #trükib tühiku
	fi
	done
echo ""
done
